"use client";
import React, { useState } from 'react';
import { Terminal, Code2, Cpu, Globe, Send, Layers, Download, Loader2 } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

export default function AIArchitectDashboard() {
  const [prompt, setPrompt] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedFiles, setGeneratedFiles] = useState<{name: string, content: string}[]>([]);

  const API_KEY = "33d9e1d1e276426bff90941b7ad9ead7";

  const handleGenerate = async () => {
    if (!prompt) return;
    setIsGenerating(true);
    
    // Simulasi pemrosesan AI tingkat tinggi
    // Di produksi, Anda akan memanggil endpoint API (OpenAI/DeepSeek/Custom)
    setTimeout(() => {
      setGeneratedFiles([
        { name: "index.html", content: "<!DOCTYPE html>\n<html>\n<head><title>App</title></head>\n<body><div id='root'></div></body>\n</html>" },
        { name: "App.tsx", content: "import React from 'react';\n\nexport default function App() {\n  return <h1>Generated by Nexus AI</h1>\n}" },
        { name: "styles.css", content: "body { background: #000; color: #fff; font-family: sans-serif; }" }
      ]);
      setIsGenerating(false);
    }, 3000);
  };

  return (
    <div className="min-h-screen flex flex-col bg-[#050505]">
      {/* Header */}
      <nav className="border-b border-white/10 p-4 flex justify-between items-center bg-[#0a0a0a]/80 backdrop-blur-md sticky top-0 z-50">
        <div className="flex items-center gap-2">
          <div className="bg-blue-600 p-1.5 rounded-lg">
            <Cpu size={24} className="text-white" />
          </div>
          <span className="text-xl font-bold tracking-tighter">NEXUS AI FORGE</span>
        </div>
        <div className="flex gap-4 text-xs font-mono text-gray-400">
          <span className="flex items-center gap-1"><span className="w-2 h-2 bg-green-500 rounded-full animate-pulse"></span> SYSTEM READY</span>
          <span className="border border-white/20 px-2 py-1 rounded">API: {API_KEY.slice(0, 8)}...</span>
        </div>
      </nav>

      <main className="flex-1 flex overflow-hidden">
        {/* Sidebar - Control Panel */}
        <aside className="w-80 border-r border-white/10 p-6 flex flex-col gap-6 bg-[#080808]">
          <div>
            <label className="text-xs font-bold text-blue-500 uppercase tracking-widest mb-3 block">Project Type</label>
            <div className="grid grid-cols-2 gap-2">
              <button className="flex flex-col items-center gap-2 p-3 rounded-xl border border-blue-500/50 bg-blue-500/10 text-blue-400">
                <Globe size={20} /> <span className="text-[10px] font-bold">WEB APP</span>
              </button>
              <button className="flex flex-col items-center gap-2 p-3 rounded-xl border border-white/5 bg-white/5 hover:bg-white/10 transition">
                <Layers size={20} /> <span className="text-[10px] font-bold">MOBILE</span>
              </button>
            </div>
          </div>

          <div className="flex-1">
            <label className="text-xs font-bold text-gray-500 uppercase tracking-widest mb-3 block">Architectural Prompt</label>
            <textarea 
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              placeholder="e.g. Build a professional crypto dashboard with real-time charts and dark mode..."
              className="w-full h-64 bg-[#0d0d0d] border border-white/10 rounded-xl p-4 text-sm focus:outline-none focus:border-blue-500/50 transition resize-none font-mono"
            />
          </div>

          <button 
            onClick={handleGenerate}
            disabled={isGenerating}
            className="w-full py-4 bg-blue-600 hover:bg-blue-500 disabled:opacity-50 text-white rounded-xl font-bold flex items-center justify-center gap-2 shadow-lg shadow-blue-600/20 transition-all active:scale-95"
          >
            {isGenerating ? <Loader2 className="animate-spin" /> : <Send size={18} />}
            {isGenerating ? "FORGING..." : "BUILD PROGRAM"}
          </button>
        </aside>

        {/* Workspace */}
        <section className="flex-1 bg-[#050505] p-6 overflow-y-auto">
          {generatedFiles.length === 0 ? (
            <div className="h-full flex flex-col items-center justify-center text-center opacity-30">
              <Code2 size={80} className="mb-4" />
              <h2 className="text-2xl font-light italic">Waiting for architecture input...</h2>
              <p className="text-sm mt-2">Enter your requirements and the AI will generate the code structure here.</p>
            </div>
          ) : (
            <div className="space-y-6">
              <div className="flex justify-between items-center">
                <h3 className="text-lg font-bold flex items-center gap-2 text-blue-400">
                  <Terminal size={20} /> GENERATED_ASSETS
                </h3>
                <button className="flex items-center gap-2 text-xs bg-white/5 hover:bg-white/10 px-4 py-2 rounded-full border border-white/10 transition">
                  <Download size={14} /> DOWNLOAD PROJECT (.ZIP)
                </button>
              </div>

              <div className="grid grid-cols-1 gap-4">
                {generatedFiles.map((file, idx) => (
                  <motion.div 
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: idx * 0.1 }}
                    key={file.name} 
                    className="border border-white/10 rounded-xl overflow-hidden"
                  >
                    <div className="bg-[#111] px-4 py-2 border-b border-white/10 flex justify-between items-center">
                      <span className="text-xs font-mono text-gray-400">{file.name}</span>
                      <span className="text-[10px] text-green-500 bg-green-500/10 px-2 py-0.5 rounded italic">ready</span>
                    </div>
                    <pre className="p-4 overflow-x-auto text-sm font-mono text-blue-100/80 bg-black">
                      <code>{file.content}</code>
                    </pre>
                  </motion.div>
                ))}
              </div>
            </div>
          )}
        </section>
      </main>
    </div>
  );
}